### ISSUE TITLE
Error in example

### ISSUE THREAD

**Issue by NoelDeMartin** [w3c/data-shapes#109]
On the first example of the shacl document ([section 1.4](http://w3c.github.io/data-shapes/shacl/#shacl-example)) there is an error because it is specified that the property `ex:ssn` can only have one value per person, but in the example `ex:Bob` has two:

```
ex:Bob
	a ex:Person ;
	ex:ssn "123-45-6789" ;
	ex:ssn "124-35-6789" .
```

I'm not doing a PR because I'm not sure if only removing one of the lines is the solution. Seems like this has been done intentionally and it isn't a typo, so there may be something else going on.

**Comment by HolgerKnublauch** [comment]
The example data has several intentional problems, including the violation of sh:maxCount 1, which gets reported in the block that has sh:sourceConstraintComponent sh:MaxCountConstraintComponent ;

**Comment by NoelDeMartin** [comment]
Ok I see, I hadn't read that far yet, my bad. Although I think it's a bit weird that the first example to appear in the document is already invalid.
