### ISSUE TITLE
Dereferencing RDF version

### ISSUE THREAD

**Issue by ktk** [w3c/data-shapes#118]
I can't seem to get any proper RDF serialization of SHACL by requesting the namespace. I currently point to the Turtle-file in this repository but it would be good to get that via content-negotiation as well.

**Comment by TallTed** [comment]
Please be more explicit about what you're trying that's failing -- i.e., what URI are you requesting, with what tool, `Accept:` header, etc?

Have you tried getting [Turtle serialization of the SHACL vocabulary](http://www.w3.org/ns/shacl.ttl), as linked from [the SHACL spec](https://www.w3.org/TR/shacl/#constraints-section)?

**Comment by ktk** [comment]
Ok I think that was my bad sorry, looking at my zsh-history it seems like I tried the URL of the spec itself this morning instead of the proper namespace URI at `http://www.w3.org/ns/shacl#`. Looks good with rapper/curl now for both Turtle and RDF/XML.
