### ISSUE TITLE
DataShapes SHACL-JS Test Suite?

### ISSUE THREAD

**Issue by ashleysommer** [w3c/data-shapes#127]
I'm just finishing up implementing SHACL-JS support in PySHACL.
I've been writing my own basic tests as I go, based on the examples in the Spec Documentation.

However I just noticed in the JSRule example, it has a namespace:
> http://datashapes.org/js/tests/rules/rectangle.test#

This url pattern is potentially indicative of a SHACL-JS TestSuite that is written somewhere.
I don't see any in the [test suites](https://github.com/w3c/data-shapes/tree/gh-pages/data-shapes-test-suite) in this repo.
Is there somewhere else I can find them, or do they not exist?

**Comment by HolgerKnublauch** [comment]
I don't have many tests for SHACL-JS but I have attached a few.

[tests-js.zip](https://github.com/w3c/data-shapes/files/5375145/tests-js.zip)
