### ISSUE TITLE
Datashapes.org content negotiation

### ISSUE THREAD

**Issue by ashleysommer** [w3c/data-shapes#141]
HTTP `GET` request to `http://datashapes.org/schema` with header `Accept: text/turtle` or `Accept: application/rdf+xml` both return the `schema.html` response, with HTML content, and content-type is always "text/html".

That breaks import statements in RDF that look like this:
```
<http://datashapes.org/sh/tests/core/complex/personexample.test>
  rdf:type owl:Ontology ;
  rdfs:label "Test of personexample" ;
  owl:imports <http://datashapes.org/schema> ;  #<-- This returns HTML
```

Note, after changing it to "<http://datashapes.org/schema.ttl>" works, however there are other inconsistencies after that:
- "http://datashapes.org/dash" works as expected, it returns exactly the format from the Accept header, and response content-type is correct
- "http://topbraid.org/tosh" does not include a `Content-Type` response header. It will return RDF in either text/turtle or rdf/xml however if you use an Accept header like "Accept: text/turtle, application/rdf+xml", it will return one of those formats but there is no way to know which one without attempting to parse the file.

**Comment by HolgerKnublauch** [comment]
The W3C is not responsible for the datashapes.org site. I will follow up with you off-list.
