### ISSUE TITLE
How to validate that a predicate is atleast provided in English?

### ISSUE THREAD

**Issue by danielbeeke** [w3c/data-shapes#144]
Hello,

I am trying to have the situation where schema:name is required in English and other languages may also be supplied.
Is this possible with SHACL?

Kind regards Daniel

My SHACL tryout that does not work.
```
    sh:property [
        sh:path schema:name ;
        sh:datatype rdf:langString ;
        sh:minCount 1 ;
        sh:xone (
        [ 
            sh:path schema:name ;
            sh:inLanguage ("en") ;
            sh:uniqueLang true ;
            sh:minCount 1 ;
            sh:maxCount 1 ;
        ] 
        [ 
            sh:path schema:name ;
            sh:uniqueLang true ;
        ] ) ;
    ] .
```

Examples of what would validate:

```
<ex:thing1> schema:name "test"@en

<ex:thing1> schema:name "test"@de, "test"@en

```

Would not validate:

```
<ex:thing1> schema:name "test"@de

<ex:thing1> schema:name "test"@de, "test"@nl

```

**Comment by danielbeeke** [comment]
It might be this use case (I think):
https://w3c.github.io/data-shapes/data-shapes-ucr/#dfn-uc21

**Comment by HolgerKnublauch** [comment]
What you are looking for is a qualified cardinality restriction. For example (untested):

    sh:property [
        sh:path schema:name ;
        ...
        sh:qualifiedMinCount 1 ;
        sh:qualifiedMaxCount 1 ;
        sh:qualifiedValueShape [
            sh:languageIn ( "en" )
        ]
    ]
    
(You had sh:inLanguage which should be sh:languageIn)

**Comment by danielbeeke** [comment]
Thanks! Great somehow I have looked over that one when I read the docs.

**Comment by HolgerKnublauch** [comment]
If your question has been answered, would you mind closing the ticket? Thanks.

**Comment by danielbeeke** [comment]
Yes it has been answered thanks!
