### ISSUE TITLE
sh:name on NodeShape ?

### ISSUE THREAD

**Issue by barthanssens** [w3c/data-shapes#145]
Seems like the domain of sh:name and sh:description is limited to PropertyShape, while they could be useful on NodeShape as well...

Actually it _is_ already being used, by e.g.  Semic.eu on the DCAT-AP metadata profile https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.1.1/dcat-ap_2.1.1_shacl_shapes.ttl

(via https://github.com/eclipse/rdf4j/issues/4289)

**Comment by HolgerKnublauch** [comment]
The rationale was that rdfs:label and rdfs:comment are already established for node shapes, so there is no reason to introduce new properties for them. And the semantics of sh:name/description are different: they mean the display name and description of the *path* not the property shape.

**Comment by HolgerKnublauch** [comment]
In preparation for a potential future SHACL WG I would like to close GitHub issues that were mainly just questions. Please reopen if you disagree.

**Comment by VladimirAlexiev** [comment]
This is a sub-issue of https://github.com/w3c/data-shapes/issues/209
