### ISSUE TITLE
maxLength-001.ttl expects support for blank nodes for sh:maxLength

### ISSUE THREAD

**Issue by cem-okulmus** [w3c/data-shapes#150]
Just as a bit of context for my use case: I am currently working on a Shacl validator that aims to use  SPARQL endpoints to implement the actual validation by encoding constraints into queries. 

I see strange situation in the test /core/node/maxLength-001.ttl which seems incompatible with the textual definition of sh:maxLength 

TEXTUAL DEFINITION
For each [value node](https://www.w3.org/TR/shacl/#dfn-value-nodes) v where the length (as defined by the [SPARQL STRLEN function](https://www.w3.org/TR/sparql11-query/#func-strlen)) of the string representation of v (as defined by the [SPARQL str function](http://www.w3.org/TR/sparql11-query/#func-str)) is greater than $maxLength, or where v is a [blank node](https://www.w3.org/TR/shacl/#dfn-blank-node), there is a [validation result](https://www.w3.org/TR/shacl/#dfn-validation-results) with v as sh:value.

In /code/node/maxLength-001.ttl we have this blank node: 

_:b34236
  rdf:type ex:TestClass ;

And it should appear also in the validation report: 

      sh:result [
          rdf:type sh:ValidationResult ;
          sh:focusNode _:b34236 ;
          sh:resultSeverity sh:Violation ;
          sh:sourceConstraintComponent sh:MaxLengthConstraintComponent ;
          sh:sourceShape ex:TestShape ;
          sh:value _:b34236 ;
        ] ;

The issue:

The Sparql "str" function _is not defined over blank nodes_ and indeed many (all?) systems that serve as Sparql endpoints do not return a value for the  str value of blank nodes. That is however exactly how maxLength (and minLength) are defined. 
So str(_:b34236) (as defined by the [SPARQL str function](http://www.w3.org/TR/sparql11-query/#func-str))  will not return a string. Of course, one could interpret this as returning the empty string, but then it becomes strange why it should violate a max length constraint.

**Comment by HolgerKnublauch** [comment]
I don't understand your concern. The textual definition explicitly states "or where v is a blank node" which is covered by that test case. In that case it doesn't matter how str() works.

**Comment by cem-okulmus** [comment]
Oh, sorry, seems I missed that part somehow. This is a non-issue then
