### ISSUE TITLE
Re 4.2.3 sh:nodeKind: add a notice about putting a constraint on nodes to be blank nodes

### ISSUE THREAD

**Issue by white-gecko** [w3c/data-shapes#25]
> The values of sh:nodeKind are one of the following six instances of the class sh:NodeKind: sh:BlankNode, sh:IRI and sh:Literal as well as the following values that represent combinations of the former three, i.e. either-or: sh:BlankNodeOrIRI, sh:BlankNodeOrLiteral and sh:IRIOrLiteral. A validation result MUST be produced for each value node that does not match the given node kind.

(Shapes Constraint Language (SHACL) W3C Editor's Draft 15 December 2016: 4.2.3 sh:nodeKind, https://w3c.github.io/data-shapes/shacl/#NodeKindConstraintComponent)

> Blank nodes do not have identifiers in the RDF abstract syntax. The blank node identifiers introduced by some concrete syntaxes have only local scope and **are purely an artifact of the serialization**.
>
> In situations where stronger identification is needed, systems MAY systematically replace some or all of the blank nodes in an RDF graph with IRIs. Systems wishing to do this SHOULD mint a new, globally unique IRI (a Skolem IRI) for each blank node so replaced.
>
> This transformation does not appreciably change the meaning of an RDF graph, provided that the Skolem IRIs do not occur anywhere else. It does however permit the possibility of other graphs subsequently using the Skolem IRIs, which is not possible for blank nodes.

(RDF 1.1 Concepts and Abstract Syntax
W3C Recommendation 25 February 2014: 3.5 Replacing Blank Nodes with IRIs, http://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/#section-skolemization)

_Proposal:_
There should be some note, that putting a constraint on nodes to be blank nodes requires special care (or even usually is not a good idea ;-) ).

_Argument:_
The existence of blank nodes is highly depends on the underlaying implementation of RDF graphs, e.g. they could be skolemized and they “are purely an artifact of the serialization”.
Further, as I understand it, it would be possible that blank nodes are mapped to named node when the graph is made [lean](https://www.w3.org/TR/2014/REC-rdf11-mt-20140225/#dfn-lean) resp. in an [instance](https://www.w3.org/TR/2014/REC-rdf11-mt-20140225/#dfn-instance) of the RDF graph.
This mean that a SHACL shape could be valid for a given graph, but not for an instance of the given graph (this might be the intended behavior in some cases, but not in others -> special care).

**Comment by HolgerKnublauch** [comment]
Note that we do rely on blank nodes in other places, most notably in the RDF representation of Path expressions (e.g. rdfs:subClassOf* can only be represented by a bnode). So if an implementation indeed decides to apply skolemization then all bets are off).

I agree we *could* add a warning by hyperlinking to the section 3.5 of RDF 1.1 Abstract Syntax. We could do this everywhere. But whether an application applies skolemization or not is outside of our control and a decision by the user of SHACL. I don't think many APIs would for example automatically apply this.

Our document includes a hyperlink to the formal definition of blank nodes in the RDF 1.1 document. With this, I believe we have fulfilled our formal obligations to make people aware of the various consequences. I am personally using blank nodes a lot and never encountered a situation in which skolemization would have been applied.

Why do you think this deserves special treatment? The part that you have highlighted (about "are purely an artifact of serialization") is only about the internal identifiers and does not change the treatment of sh:BlankNode in sh:nodeKind.

**Comment by HolgerKnublauch** [comment]
Hi Natanael, we have recently changed to a more formal use of GitHub and it was suggested that we try to get feedback from the submitter on whether they are OK with closing these tickets. It would help us if you could clarify whether you can live with the current state.
