### ISSUE TITLE
References not rendering (Firefox 51.0.1)

### ISSUE THREAD

**Issue by simonstey** [w3c/data-shapes#26]
On Win7, Firefox (51.0.1) doesn't render any references (e.g., "http://w3c.github.io/data-shapes/shacl/#bib-RFC2119") -> Appendix G - References is missing. 

They work fine on Google Chrome though.

**Comment by HolgerKnublauch** [comment]
Hmm, seems to work on Firefox 51 Windows 10 and I don't have any older machine. So I am not sure what I can do about it. Is this a consistent problem or just temporary?

**Comment by simonstey** [comment]
> Is this a consistent problem or just temporary?

consistent.. it seems to work fine with any other browser though.

**Comment by HolgerKnublauch** [comment]
Simon, as I cannot reproduce this and it would be a bug in the stylesheet or respec, could we close this ticket?

**Comment by simonstey** [comment]
ah yes..
