### ISSUE TITLE
Wrong predicate in sh:disjoint description

### ISSUE THREAD

**Issue by robert-david** [w3c/data-shapes#28]
The following description of sh:disjoint states sh:equals as predicate to compare with. Shouldn't this be sh:path?

---
4.5.2 sh:disjoint

sh:disjoint specifies the condition that the set of value nodes is disjoint with the set of objects of the triples that have the focus node as subject and the value of sh:equals as predicate.

**Comment by HolgerKnublauch** [comment]
Thank you! I must have copied and pasted this from sh:equals. It should have been sh:disjoint (the sh:path comes into play via the "value nodes"). Fixed:

https://github.com/w3c/data-shapes/commit/b22faf7409d319798f2d0559901eec40911c8f43
