### ISSUE TITLE
sh:query non-normative?

### ISSUE THREAD

**Issue by jhodgesatsbl** [w3c/data-shapes#29]
Back in 2016 I made a comment about SPARQL constraints in SHACL, and mentioned our need for SPARQL constraints support in SHACL. My concerns were met with statements about how many implementations should exist to make SPARQL constraints part of the current release; a comment that I considered (and consider) orthogonal to the discussion. In reading the current specification I see that SPARQL SHACL constraints are considered non-normative. Will this charge the specification or related implementations because the basic set of constraints offered in the specification are only minimally useful and I could implement them myself. The much more interesting (and complicated) constraints are intra-object constraints which can only be implemented with SPARQL.

**Comment by HolgerKnublauch** [comment]
SHACL-SPARQL is normative. sh:query has been renamed to sh:select and is used in values of sh:sparql. Which statements in the document give you the impression that these features are not normative? The SPARQL queries that used to be in section 4 were only defining the semantics of the Core constraint types, while the actual SPARQL extension mechanism is covered by sections 5 and 6.

**Comment by HolgerKnublauch** [comment]
In a private message, Jack confirmed that this was a misunderstanding. Closing.
