### ISSUE TITLE
what about reification?

### ISSUE THREAD

**Issue by antonkulaga** [w3c/data-shapes#3]
I have not found anything about reification in both ShEx and SHACL :( In the same time it is extremely useful feature. Statements come from different places and can have extremely important meta-information about them (author, degree of certainty, source and so on) I do not see how can I put contstrains on that with ShEx/SHACL :-(

**Comment by HolgerKnublauch** [comment]
Hi Anton, (I am not sure if using GitHub Issues is actually the best way to discuss this - we have public mailing lists for feedback).

Anyway, could you clarify how SHACL's use of reification would be different from RDFS'? In particular, anyone could define constraints on rdfs:Statement.

**Comment by antonkulaga** [comment]
Let's consider a simple examples, just from your specification:

``` turtle
my:UserShape a sh:Shape ;
    sh:property [                                     
        sh:predicate    foaf:name ;                   
        sh:valueType    xsd:string ;                  
        sh:minCount 1 ; sh:maxCount 1                 
    ] ;                                               
    sh:property [                                     
        sh:predicate    foaf:mbox ;                   
        sh:nodeKind     sh:IRI ;                      
        sh:minCount 1                                 
    ] .    
```

Here we have user specification with foaf:name and foaf:mbox properties. In our database some information is provided by user himself and some is suggested by other users (just in case it is what I have in the app I develop, the shapes are a bit different the quoted one but most of the data has source). If we display only official information we should show only the statements provided by the user himself, so both statements that <:user> foaf:name <some string> and  <user> foaf:mbox some:IRI must have dcterms:creator with the same IRI as user.
At the moment, I see **no ways** to express it with either SHACL or SHEX. 

And I also want to emphasize one important moment:
1) In many applications all statements will have either rdfs:Statement or (more likely) context or statement IDs (like in http://wiki.blazegraph.com/wiki/index.php/Reification_Done_Right ). Simply because we aggregate information from multiple source and not all sources can be equally treated.
2) Statement restrictions are very common, so the way to write them should not be very verbose or complex. Writing several subshapes for any property where I want to control reification will definitely make developers crazy and will lead to a lot of code in apps and libraries that use SHACL shapes.

**Comment by ericprud** [comment]
- Anton Kulaga notifications@github.com [2015-06-04 00:03-0700]
  > Let's consider a simple examples, just from your specification. We have a constraint about the 
  > 
  > `turtle
  > my:UserShape a sh:Shape ;
  >     sh:property [                                     
  >         sh:predicate    foaf:name ;                   
  >         sh:valueType    xsd:string ;                  
  >         sh:minCount 1 ; sh:maxCount 1                 
  >     ] ;                                               
  >     sh:property [                                     
  >         sh:predicate    foaf:mbox ;                   
  >         sh:nodeKind     sh:IRI ;                      
  >         sh:minCount 1                                 
  >     ] .    
  >`
  > Here we have user specification with foaf:name and foaf:mbox properties. In our database some information is provided by user himself and some is suggested by other users (just in case it is what I have in an app I develop the shape are a bit different but all the data has source). If we display only official information we should show only the statements provided by the user himself, so both statements that <:user> foaf:name <some string> and  <user> foaf:mbox some:IRI must have dcterms:creator with the same IRI as user.
  > At the moment, I see no ways to express it with either SHACL or SHEX. 

ShExC doesn't have the RDR << >> syntax, but I believe it does express what you want:

http://www.w3.org/2013/ShEx/FancyShExDemo?schema=PREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0Astart%20%3D%20%7B%0A%20%20%5Erdf%3Asubject%20%7Brdf%3Apredicate%20(foaf%3Aname)%2C%20rdf%3Aobject%20xsd%3Astring%7D%2C%0A%20%20%5Erdf%3Asubject%20%7Brdf%3Apredicate%20(foaf%3Ambox)%2C%20rdf%3Aobject%20IRI%7D%0A%7D&data=PREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0A%3Cs1%3E%0A%20%20rdf%3Asubject%20%3CX%3E%3B%0A%20%20rdf%3Apredicate%20foaf%3Aname%3B%0A%20%20rdf%3Aobject%20%22Alice%22.%0A%0A%3Cs2%3E%0A%20%20rdf%3Asubject%20%3CX%3E%3B%0A%20%20rdf%3Apredicate%20foaf%3Ambox%3B%0A%20%20rdf%3Aobject%20%3Calice%40example.org%3E.%0A&starting-nodes=%3CX%3E&colorize=true

> And I also want to emphasize one imporant moment:
> 1) In many applications all statements will have either rdfs:Statement or (must more likely) context or statement IDs (like in http://wiki.blazegraph.com/wiki/index.php/Reification_Done_Right ). Simply because we aggregate information with multiple source and not all sources can be equally treated.
> 2) Statement restrictions are very common, so the way to write them should not be very verbose or complex. Writing several subshapes for any property where I want to control reification will definetely mean me crazy and will lead to a lot of code in my library.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/w3c/data-shapes/issues/3#issuecomment-108757418

## 

-ericP

office: +1.617.599.3509
mobile: +33.6.80.80.35.59

(eric@w3.org)
Feel free to forward this message to any list for any purpose other than
email address distribution.

There are subtle nuances encoded in font variation and clever layout
which can only be seen by printing this message on high-clay paper.

**Comment by antonkulaga** [comment]
Thanks for the answer. But how can it be explained in terms of abstract syntax? (actually it is what I care most of all, as I am going to implement shex for banana-rdf and there for each abstract syntax element there will be a case class).
In ShEx AST description ( http://www.w3.org/2013/ShEx/Definition.html ) I do not see how I can express statements about statements. I see that ArcRules is for properties, but how can I add reification for each property there? Or maybe this AST spec if outdated and I should use another one?

**Comment by ericprud** [comment]
- Eric Prud'hommeaux eric@w3.org [2015-06-04 09:48-0400]
  > \* Anton Kulaga notifications@github.com [2015-06-04 00:03-0700]
  > > Let's consider a simple examples, just from your specification. We have a constraint about the 
  > > 
  > > `turtle
  > > my:UserShape a sh:Shape ;
  > >     sh:property [                                     
  > >         sh:predicate    foaf:name ;                   
  > >         sh:valueType    xsd:string ;                  
  > >         sh:minCount 1 ; sh:maxCount 1                 
  > >     ] ;                                               
  > >     sh:property [                                     
  > >         sh:predicate    foaf:mbox ;                   
  > >         sh:nodeKind     sh:IRI ;                      
  > >         sh:minCount 1                                 
  > >     ] .    
  > >`
  > > Here we have user specification with foaf:name and foaf:mbox properties. In our database some information is provided by user himself and some is suggested by other users (just in case it is what I have in an app I develop the shape are a bit different but all the data has source). If we display only official information we should show only the statements provided by the user himself, so both statements that <:user> foaf:name <some string> and  <user> foaf:mbox some:IRI must have dcterms:creator with the same IRI as user.
  > > At the moment, I see no ways to express it with either SHACL or SHEX. 
  > 
  > ShExC doesn't have the RDR << >> syntax, but I believe it does express what you want:
  > 
  > http://www.w3.org/2013/ShEx/FancyShExDemo?schema=PREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0A%0Astart%20%3D%20%7B%0A%20%20%5Erdf%3Asubject%20%7Brdf%3Apredicate%20(foaf%3Aname)%2C%20rdf%3Aobject%20xsd%3Astring%7D%2C%0A%20%20%5Erdf%3Asubject%20%7Brdf%3Apredicate%20(foaf%3Ambox)%2C%20rdf%3Aobject%20IRI%7D%0A%7D&data=PREFIX%20foaf%3A%20%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0A%0A%3Cs1%3E%0A%20%20rdf%3Asubject%20%3CX%3E%3B%0A%20%20rdf%3Apredicate%20foaf%3Aname%3B%0A%20%20rdf%3Aobject%20%22Alice%22.%0A%0A%3Cs2%3E%0A%20%20rdf%3Asubject%20%3CX%3E%3B%0A%20%20rdf%3Apredicate%20foaf%3Ambox%3B%0A%20%20rdf%3Aobject%20%3Calice%40example.org%3E.%0A&starting-nodes=%3CX%3E&colorize=true

I guess a sensible ShExC grammar extension for RDR whould be to add
<<>>s around the predicate and object, implying that triple constriant
with a pattern like "foaf:name xsd:string" is interpreted as
"^rdf:subject {rdf:predicate (foaf:name), rdf:object xsd:string}"

One coudl also replace {}s with <<>>s in a type declaration to apply
that to all nested triple constraints.

http://www.w3.org/2005/01/yacker/uploads/ShEx2RDR?lang=perl&text=start+%3D+%3C%3C%0D%0A++foaf%3Aname+xsd%3Astring%2C%0D%0A++foaf%3Ambox+IRI%0D%0A%3E%3E%0D%0A%0D%0Amy%3AX+{%0D%0A++%3C%3Cfoaf%3Aname+xsd%3Astring%3E%3E%2C%0D%0A++foaf%3Ambox+IRI%0D%0A}&action=validate+text

> > And I also want to emphasize one imporant moment:
> > 1) In many applications all statements will have either rdfs:Statement or (must more likely) context or statement IDs (like in http://wiki.blazegraph.com/wiki/index.php/Reification_Done_Right ). Simply because we aggregate information with multiple source and not all sources can be equally treated.
> > 2) Statement restrictions are very common, so the way to write them should not be very verbose or complex. Writing several subshapes for any property where I want to control reification will definetely mean me crazy and will lead to a lot of code in my library.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/w3c/data-shapes/issues/3#issuecomment-108757418
> 
> ## 
> 
> -ericP
> 
> office: +1.617.599.3509
> mobile: +33.6.80.80.35.59
> 
> (eric@w3.org)
> Feel free to forward this message to any list for any purpose other than
> email address distribution.
> 
> There are subtle nuances encoded in font variation and clever layout
> which can only be seen by printing this message on high-clay paper.

## 

-ericP

office: +1.617.599.3509
mobile: +33.6.80.80.35.59

(eric@w3.org)
Feel free to forward this message to any list for any purpose other than
email address distribution.

There are subtle nuances encoded in font variation and clever layout
which can only be seen by printing this message on high-clay paper.
