### ISSUE TITLE
Feedback: Evidence of interest in SHACL

### ISSUE THREAD

**Issue by gregor5555** [w3c/data-shapes#33]
I am developing a semantic data solution for a mayor financial institution and use SHACL constraints to validate user input for classes. It is in my interest to see SHACL become a W3C standard to have planning reliability for future development efforts. 
Also in light of the anticipated FIBO adoption within the financial industry, I believe SHACL will play a crucial role in the cross-firm data integration by providing a common way to validate a constraint graph against a data graph.

Sincerely,
Gregor Wobbe

**Comment by kurtcagle** [comment]
I'm currently exploring an implementation of a SHACL processor on the MarkLogic 9 server environment. I'll be making a recommendation to the engineering team there that they consider this for the github "additions" this time around, as most of the API changes for 9 are pretty much baked in at this stage.

**Comment by HolgerKnublauch** [comment]
@kurtcagle this sounds great. If there is anything semi-official that we could include into the Implementations section (see for example the mentioning of OpenLink at https://www.w3.org/2014/data-shapes/wiki/Main_Page#Implementations) then please let us know. Evidence for adoption and plans to implement will inform the W3C with their (critical) decision on whether to turn SHACL into a Candidate Recommendation.
