### ISSUE TITLE
Page not found for ldom.ttl

### ISSUE THREAD

**Issue by nimonika** [w3c/data-shapes#4]
This link, as provided on https://w3c.github.io/data-shapes/data-shapes-primer/ldom-primer.html
does not resolve https://w3c.github.io/data-shapes/data-shapes-core/ldom.ldom.ttl

**Comment by simonstey** [comment]
please use https://w3c.github.io/data-shapes/shacl and https://w3c.github.io/data-shapes/shacl/shacl.shacl.ttl respectively.
