### ISSUE TITLE
String without the notion of a character

### ISSUE THREAD

**Issue by r12a** [w3c/data-shapes#43]
[comment from  @fsasaki ]
5. On string-based constraints components This section
http://w3c.github.io/data-shapes/shacl/#core-components-string

defines the length of a string, without the notion of a character.

Probably the implementations will just rely on SPARQL 1.1. here as well, but this should be pointed out explicitly, see the language matching comment.

[additional comment from i18n telecon]
Don't base 'character' on 16-bit code units. Use Unicode code points.

**Comment by HolgerKnublauch** [comment]
In the textual definitions of sh:maxLength and sh:minLength, we do have hyperlinks to the SPARQL 1.1 str function, which handles this. Again, I am not convinced that anything else needs to be said here, and welcome group discussion.

**Comment by fsasaki** [comment]
I guess you mean the hyperlink in this sentence.

> For each value node v where the length of the string representation of v (as defined by the SPARQL str function) is greater than $maxLength, or where v is a blank node, there is a validation result with v as sh:value.

I would see a value in making the notion of a string more explicit. See also the additional comment

> Don't base 'character' on 16-bit code units. Use Unicode code points.

**Comment by HolgerKnublauch** [comment]
We have added a reference to the SPARQL STRLEN function to clarify the semantics, see https://www.w3.org/2017/03/22-shapes-minutes.html#item04

**Comment by fsasaki** [comment]
IMO looks good, thanks
