### ISSUE TITLE
clarification on the semantics of sh:qualifiedValueShapesDisjoint

### ISSUE THREAD

**Issue by iovka** [w3c/data-shapes#47]
Above is the example from the current version of the SHACL specification.
Can you please clarify the semantics by indicating which of the below hands (ex:hand1, ..., ex:hand4) satisfy the ex:HandShape ?

Here is where my doubts come from.

- If only ex:hand1 satisfies, then do we really need the sh:qualifiedValueShapesDisjoint true, or won't we get the same result without it ?

- If ex:hand2 satisfies (which seems most desirable), then isn't the case that ex:hand3 also satisfies because of the symmetry between the thumb and finger constraints ?

Thanks in advance.

ex:HandShape
	a sh:NodeShape ;
	sh:targetClass ex:Hand ;
	sh:property [
		sh:path ex:digit ;
		sh:qualifiedValueShape [ sh:class ex:Thumb ] ;
		sh:qualifiedValueShapesDisjoint true ;
		sh:qualifiedMinCount 1 ;
		sh:qualifiedMaxCount 1 ;
	] ;
	sh:property [
		sh:path ex:digit ;
		sh:qualifiedValueShape [ sh:class ex:Finger ] ;
		sh:qualifiedValueShapesDisjoint true ;
		sh:qualifiedMinCount 4 ;
		sh:qualifiedMaxCount 4 ;
	] .

ex:hand1 a ex:Hand ;
         ex:digit [a ex:Thumb] ,
                  [a ex:Finger] ,
                  [a ex:Finger] ,
                  [a ex:Finger] ,
                  [a ex:Finger] .

ex:hand2 a ex:Hand ;
         ex:digit [a ex:Thumb ; a ex:Finger ] ,
                  [a ex:Finger] ,
                  [a ex:Finger] ,
                  [a ex:Finger] ,
                  [a ex:Finger] .

ex:hand3 a ex:Hand ;
         ex:digit [a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] .

ex:hand4 a ex:Hand ;
         ex:digit [a ex:Finger ; a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] ,
                  [a ex:Finger ; a ex:Thumb ] .

**Comment by HolgerKnublauch** [comment]
Yes only hand1 satisfies this shape (you could try it out at http://shacl.org/playground if you like).

If you remove the disjointness, you get the same number of violations but for with different reasons. For example hand2 would fail because it has more than 4 fingers while otherwise it fails because it has no well-formed thumb.

**Comment by white-gecko** [comment]
As I understand it, the disjoint is best depicted by the violation of 

```
ex:hand1 a ex:Hand ;
ex:digit [a ex:Thumb, ex:Finger] ,
    [a ex:Finger] ,
    [a ex:Finger] ,
    [a ex:Finger] .
```

If you set `sh:qualifiedValueShapesDisjoint true`  in both shapes this example would be valid.
