### ISSUE TITLE
status of advice in test suite document on validation reports

### ISSUE THREAD

**Issue by pfps** [w3c/data-shapes#56]
There is wording in the SHACL Test Suite and Implementation Report at
http://w3c.github.io/data-shapes/data-shapes-test-suite/ to the effect that
certain validation reports are not allowed.

For example, there is "The actual results also must not depend on subclass
relationships, so that instances of subclasses of sh:ValidationReport and
sh:ValidationResult must have these as their (only) rdf:type values."

This seems to state that to pass compliance a SHACL implementation MUST
produce validation results where the typing of the validation report node
and any validation result nodes do not depend on rdfs:subclassOf triples in
the validation report.  However, this kind of typing is allowed in the
definition of validation reports so the test suite is disallowing certain
compliant SHACL implementations.

**Comment by HolgerKnublauch** [comment]
No this is not what the document says. All we say is that *prior to the comparison* the test harness needs to post-process the result graph delivered by the engine to fit a certain structure.

**Comment by pfps** [comment]
Here is part of the wording: "Let actual be the results graph produced by the validation, i.e. the validation report. Before comparing these results with the expected results, the actual validation report must not include any "nested" results, via sh:details."  This says quite clearly that the actual validation report must nod include any nested results, not that the actual validation report is modified in some way.

**Comment by HolgerKnublauch** [comment]
The descriptions in the Test Suite did not seem to have stopped other people from submitting implementation reports. I wonder why nobody else finds the "issues" that you run into problematic at all. Even with the wording above it should be clear that the result graph can be modified by the Test runner.

Anyway, I have added a sentence "The test framework may post-process this results graph to ensure the following preconditions".

Assuming this clarifies this, I am closing this ticket. Please reopen if you still don't understand what needs to be implemented here.

**Comment by pfps** [comment]
I expect that the reason that other implementers have not run into these problems with the test suite is that their implementation reports look just like the "expected" ones.  When this is the case, no changes have to be made to the actual reports at all.  Conformant actual results do not look like "expected" results require close examination of the test suite process, exposing its continuing flaws.

**Comment by irenetq** [comment]
Does the added clarification makes it clear to you what needs to happen? If not, please propose a sentence that would make it clear.

**Comment by pfps** [comment]
Yes the current wording is adequate on this point.
