### ISSUE TITLE
SHACL requirements in non-normative parts of the document

### ISSUE THREAD

**Issue by pfps** [w3c/data-shapes#57]
There are still aspects of SHACL that appear only in non-normative
(informative) sections of the document.  For example, a part of Section
2.1.5 labelled as informative states a requirement on the values of
sh:resultMessage in validation results.  This requirement is not stated in
any normative part of the document.

This issue has been previously reported.

**Comment by HolgerKnublauch** [comment]
I don't see anything non-normative in 2.1.5 that is not also covered by 3.6.2.7 which is normative. Please clarify, also be explicit about which other parts you think are misplaced.

**Comment by pfps** [comment]
3.2.6.7 does not say what is supposed to be done, just that something should be done, and points to 2.1.5 for more information where the actual generation is only in a non-normative section.

**Comment by pfps** [comment]
The change is fine. 

This is a non-editorial change in that it places more normative conditions on implementations.

That said, the only problem was that the requirement was in a non-normative section of the document so I don't see any reason to hold up further progress because of this issue.
