### ISSUE TITLE
requirements on sh:message not checked in test cases process

### ISSUE THREAD

**Issue by pfps** [w3c/data-shapes#60]
There are requirements on sh:resultMessage that are not checked by the
process in the test suite document.

(non-normative) 
2.1.5 Declaring Messages for a Shape
If a shape has at least one value for sh:message in the shapes graph, then
all validation results produced as a result of the shape will have exactly
these messages as their value of sh:resultMessage,

(normative)
5.3.2 Mapping of Solution Bindings to Result Properties 
sh:resultMessage 	
1. The binding for the variable message
2. For SPARQL-based constraints: The values of sh:message of the
   SPARQL-based constraint. For SPARQL-based constraint components: The
   values of sh:message of the validator of the SPARQL-based constraint
   component.  
3. For SPARQL-based constraint components: The values of sh:message of the
   SPARQL-based constraint component.

**Comment by HolgerKnublauch** [comment]
Not sure what you are referring to. Are you asking for specific test cases to cover sh:message better, or do you think the test framework needs to change. If the latter, what do you suggest?

**Comment by pfps** [comment]
The test framework needs to change to not remove sh:resultMessage triples.

**Comment by HolgerKnublauch** [comment]
I have addressed this by adding a special rule for handling sh:resultMessage, and added a corresponding test case. See commit above. This makes it possible for certain tests to specifically test for the presence of certain messages without requiring specific messages elsewhere.

**Comment by pfps** [comment]
I think that the logic is the wrong way around - it should be the subject that is checked, but I don't think that even that is correct.

**Comment by HolgerKnublauch** [comment]
The approach seems to have been clear enough for those who have submitted implementation reports. I see no need to complicate this any further. The test suite never claimed to be complete or replace what's already stated in the spec.

**Comment by pfps** [comment]
No longer worth worrying about at this time.
