### ISSUE TITLE
behaviour of SHACL Core implementation on shapes graphs with ill-formed SHACL-SPARQL constructs

### ISSUE THREAD

**Issue by pfps** [w3c/data-shapes#65]
Is the behaviour of SHACL Core implementations undefined if the only invalid
part of a shapes graph is a SHACL-SPARQL construct?  For example, is the
behaviour of a SHACL Core implemenatation defined on
  ex:s1 a sh:NodeShape ;
    sh:targetNode ex:i ;
    sh:class ex:C .
  ex:s2 a sh:NodeShape ;
    sh:targetNode ex:i ;
    sh:sparql [ ] .

**Comment by HolgerKnublauch** [comment]
Pure SHACL core implementations ignore SHACL-SPARQL syntax rules and see no special meaning in sh:sparql.

**Comment by pfps** [comment]
Is this a requirement for SHACL Core processors?  Where is this stated?

**Comment by HolgerKnublauch** [comment]
It is stated because the syntax rules of SHACL-SPARQL are in Part 2 of the document, while SHACL Core is in Part 1.

**Comment by pfps** [comment]
I don't see anything in the document indicating that SHACL Core processors *MUST* ignore SHACL-SPARQL constructs - neither wording nor organization.

**Comment by HolgerKnublauch** [comment]
I disagree with your assessment, see my previous comment.

**Comment by irenetq** [comment]
The working group has reviewed this issue at the meeting on April 24th and decided that the text in the spec makes it clear that SHACL-SPARQL constructs carry no meaning for the processors that only support SHACL Core. 

In other words, to the SHACL Core-only processor there is not difference between 

{my:Shape sh:sparql "a"} 

or 

{my:Shape sh:sparql [
		sh:message "Values are literals with German language tag." ;
		sh:prefixes ex: ;
		sh:select """
			SELECT $this ?value
			WHERE {
				$this $PATH ?value .
				FILTER (!isLiteral(?value) || !langMatches(lang(?value), "de"))
			}
			""" ;
	]} .  
or 

{my:Shape my:property [
		sh:message "Values are literals with German language tag." ;
		sh:prefixes ex: ;
		sh:select """
			SELECT $this ?value
			WHERE {
				$this $PATH ?value .
				FILTER (!isLiteral(?value) || !langMatches(lang(?value), "de"))
			}
			""" ;
	] }.  

SHACL Core only processors treat triples with sh:sparql predicate exactly the same way as triples with some arbitrary non SHACL predicate. Simply as RDF statements with no special semantics understood by the processor.

**Comment by irenetq** [comment]
I think this issue is redundant given issue #63. Since response to issue 63 says that triples with sh:sparql predicate carry no special meaning to SHACL Core-only processors, then the question about the query being ill formed is a mute point.

**Comment by pfps** [comment]
I have responded in issue 63.

**Comment by HolgerKnublauch** [comment]
This has been clarified and handled by #63.

**Comment by irenetq** [comment]
We will consider the issue addressed unless we hear back from the submitter within 5 days of the last WG response comment.

**Comment by irenetq** [comment]
Adding a link to the wiki page for the formal objection https://www.w3.org/2014/data-shapes/wiki/PRFO1
