### ISSUE TITLE
test cases process removes too much

### ISSUE THREAD

**Issue by pfps** [w3c/data-shapes#67]
The test cases process removes all triples except for those with certain predicates. 

This is much too aggressive as it removes, for example, path-forming triples.

**Comment by HolgerKnublauch** [comment]
I have added clarification that blank node structures under sh:resultPath must be preserved. Do you have any other examples of where too many triples are deleted?

**Comment by pfps** [comment]
Type links to sh:validationReport should not be removed.

**Comment by HolgerKnublauch** [comment]
Ok, done, also: sh:conforms and sh:result.

**Comment by pfps** [comment]
Still removing too much, but it's not worth worrying about except to note that it is still removing to much.
