### ISSUE TITLE
How does sh:hasValue should validate against focus nodes?

### ISSUE THREAD

**Issue by MiguelAraCo** [w3c/data-shapes#90]
I understand the behavior it should have when it is part of a `sh:PropertyShape`. But how should it be validated if it is part of a `sh:NodeShape`?

Example:

```
<NotTheFocusNode>
  ex:property "Hello".
<NotTheFocusNodeEither>
  ex:property "Hello", "World".

<NodeShape>
  ex:targetObjectsOf ex:property;
  sh:hasValue "Hello".
```

In this example the focus nodes (and value nodes) are `Hello`, `Hello` and `World`. Because we are treating with focus nodes I would assume each one is validated separately. To quote @HolgerKnublauch  "forming a set of 1 always". If that's the case, the focus node `World` would produce a result.

Is this the expected behavior?

**Comment by HolgerKnublauch** [comment]
Yes, there will be a violation of World (only). (Assuming you mean sh:targetObjectsOf, not ex:targetObjectsOf).

**Comment by MiguelAraCo** [comment]
Perfect, thanks!
