### ISSUE TITLE
Can sh:hasValue point to multiple values?

### ISSUE THREAD

**Issue by MiguelAraCo** [w3c/data-shapes#91]
The specification doesn't explicitly say it can't but it could be implicitly inferred that it can't due to the following statement:

> sh:hasValue specifies the condition that at least one value node is equal to the given RDF term.

**Comment by MiguelAraCo** [comment]
Also:

> sh:hasValue - A specific required value.

So would this be an ill-formed shape?

```
<PropertyShape>
  sh:path ex:property ;
  sh:hasValue "Hello!" ;
  sh:hasValue "World" .
```

**Comment by HolgerKnublauch** [comment]
There is no such restriction. If there were a max 1 restriction then it would show up in the "Parameters" table at https://www.w3.org/TR/shacl/#HasValueConstraintComponent. In the example above, both values must be present for the property.

**Comment by MiguelAraCo** [comment]
👍
