### ISSUE TITLE
Validate that graph contains a node with a specific type

### ISSUE THREAD

**Issue by MiguelAraCo** [w3c/data-shapes#93]
I'm having a hard time figuring out how to create a shape that validates the following condition:

> The data graph must contain a node with a specific type (e.g. ex:Product)

My first approach was to use a shape graph like the following one:

```
<ContainsOneProduct>
	sh:NodeShape ;
	sh:targetClass ex:Product ;
	sh:node
		<ContainsOneProduct#graph-contains-Product> ,
		<ContainsOneProduct#graph-contains-only-one-Product> ,
	.
<ContainsOneProduct#graph-contains-Product>
	a sh:NodeShape ;
	sh:message "The graph must contain a 'ex:Project'"@en ;
	sh:minCount "1"^^xsd:integer .
<ContainsOneProduct#graph-contains-only-one-Product>
	a sh:NodeShape ;
	sh:message "The graph mustn't contain more than one 'ex:Project'"@en ;
	sh:maxCount "1"^^xsd:integer .
```

This can't be done because `sh:NodeShape`s can't have `sh:minCount` or `sh:maxCount`. So what would be a way to validate this condition?

**Comment by HolgerKnublauch** [comment]
See https://www.w3.org/wiki/SHACL/Examples

**Comment by MiguelAraCo** [comment]
Awesome, thanks!

**Comment by mielvds** [comment]
@HolgerKnublauch would a shortcut for https://www.w3.org/wiki/SHACL/Examples be a valid suggestion for 1.2?

**Comment by HolgerKnublauch** [comment]
@mielvds do you mean a shortcut to the Wiki page (I don't think so) or for this particular trick with the inversePath of rdf:type? If the latter, what do you have in mind?

**Comment by mielvds** [comment]
I meant introducing something like `<> a sh:NodeShape ; sh:minCount "1"^^xsd:integer .` that would be equivalent to this trick, but mentioning this trick in a FAQ somewhere would also be very helpful (obvious as it is, I didn't think of it ;))
